In [1]:
print('Hello')

Hello

In [2]:
print("bhakti")

bhakti

In [ ]:
a=10
b=20
c=a+b
print(c)

30

In [4]:
a=int(input("Enter value of A"))
b=int(input("Enter value of B"))
c=a+b
print("Addition",c)

Addition 3

In [5]:
print('Bhakti')

Bhakti

In [9]:
name=input("Enter your name")
print('Your name is' , name)

Your name is bhakti

In [10]:
name=input("Enter your name")
if name=="Bhakti":
  print("Hloo bhakti good morning")

Hloo bhakti good morning

the upper code is example of if statement

In [ ]:
name=input("Enter your name")
if name=="Bhakti":
  print("Hloo bhakti good morning")
else:
  print("Hloo good morning")

Enter your nameRam
Hloo good morning

the upper code is the example of if else statement

In [ ]:
name="Trisha"
if name=="Trisha":
  print("Hloo Trisha good morning")
elif name=="Bhakti":
  print("Hloo Bhakti good morning")
else:
  print("Hloo good morning")

Hloo Trisha good morning

In [ ]:
if name=="Trisha":
  print("Hloo Trisha good morning")
elif name=="Bhakti":
  print("Hloo Bhakti good morning")
else:
  print("Hloo good morning")

Hloo Trisha good morning

In [ ]:
s="prisha"
for x in s:
  print(x)

p
r
i
s
h
a

the upper code is of for loop

to print hloo 10 times

In [ ]:
for x in range (10):
   print("Hloo")

Hloo
Hloo
Hloo
Hloo
Hloo
Hloo
Hloo
Hloo
Hloo
Hloo

to display  no from 0 to 100

In [ ]:
for x in range (10):
   print(x)

0
1
2
3
4
5
6
7
8
9

In [ ]:
list=eval(input("Enter list"))
sum=0
for x in list:
  sum=sum+x
print("sum=",sum)

Enter list3,33,3,3,3,
sum= 45

the upper code is to print the sum of no present inside the list

*code* for while loop

In [ ]:
x=1
while x<=1:
 print(x)
x=x-1

Streaming output truncated to the last 5000 lines.
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

In [ ]:
fruits=["Apple","banana","chiku"]
print(fruits)

['Apple', 'banana', 'chiku']

In [ ]:
fruits=["Apple","banana","chiku"]
print(fruits[0])

Apple

In [ ]:
fruits=["Apple"]
fruits.append("Mango")
print(fruits)

['Apple', 'Mango']

In [ ]:
fruits=["Apple","banana","chiku"]
fruits.extend(("Mango","avacado"))
print(fruits)

['Apple', 'banana', 'chiku', 'Mango', 'avacado']

In [ ]:
nums=[10,20,30,40,56]
nums.pop(0)
print(nums)

In [ ]:
nums=[10,20,30,40,56]
nums.clear()
print(nums)

[]

In [ ]:
nums=[10,20,30,40,56]
# The insert method expects two arguments: index and value.
# For example, to insert 45 at index 0:
nums.insert(0, 45)
print(nums)

[45, 10, 20, 30, 40, 56]

In [ ]:
nums=[78,54,65,32,43]
print(nums.count(54))

1

In [ ]:
nums=[10,80,30,40,56]
nums.sort()
print(nums)

[10, 30, 40, 56, 80]

In [ ]:
nums=[10,20,30,40,56]
nums.reverse()
print(nums)

[56, 40, 30, 20, 10]

In [ ]:
a=[1,2,3,4,5]
b=a.copy()
print(b)

[1, 2, 3, 4, 5]

In [ ]:
nums=[10,20,30,40,56]
print(len(nums))
print(nums)

5
[10, 20, 30, 40, 56]

In [ ]:
nums=[10,20,30,40,56]
print(max(nums))
print(nums)

56
[10, 20, 30, 40, 56]

In [ ]:
nums=[10,20,30,40,56]
print(min(nums))

10

In [ ]:
nums=[10,20,30,40,56]
print(sum(nums))

156

In [ ]:
a=(23,45,67,89)
print(a.count(45))

1

In [ ]:
a=(23,45,67,89)
print(a.index(67))

2

In [ ]:
fruits=["Apple","baanana","papaya","watermelon"]
print(fruits[2])

papaya

Slicing extracts a portion of a sequence (list, tuple, string, etc.) using the syntax sequence[start:stop:step].
Basic syntax
pythonlst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

start: index where slice begins (inclusive). Default is 0.
stop: index where slice ends (exclusive). Default is length of sequence.
step: gap between elements. Default is 1.

In [ ]:
lst = [5, 10, 15, 20, 25, 30, 35]
lst[2:5]

[15, 20, 25]

In [ ]:
lst = [5, 10, 15, 20, 25, 30, 35]
lst[:5]

[5, 10, 15, 20, 25]

In [ ]:
lst = [5, 10, 15, 20, 25, 30, 35]
lst[3:]

[20, 25, 30, 35]

In [ ]:
lst = [5, 10, 15, 20, 25, 30, 35]
lst[-3:]

[25, 30, 35]

In [ ]:
lst = [5, 10, 15, 20, 25, 30, 35]
lst[::-1]

[35, 30, 25, 20, 15, 10, 5]

In [ ]:
lst = [5, 10, 15, 20, 25, 30, 35]
lst[::-2]

[35, 25, 15, 5]

In [ ]:
lst = [5, 10, 15, 20, 25, 30, 35]
lst[1:6:2]

[10, 20, 30]

Data Structures
Set
1. A set is a built-in data type in Python used to store multiple unique values in a single variable.
2. No duplicates: {1, 2, 2, 3} becomes {1, 2, 3}
3. Unordered: items have no fixed position, so no indexing (set[0] doesn't work)
4. Mutable: you can add/remove
5. We can apply multiple mathematical operations like union,intersection,differences etc on set object
6. Haterogenous(Diff data types) elements are allowed
7. Set Operations
1. Union |
Combines all unique elements.
2. Intersection &
Common elements.
3. Difference -
Elements present in first set only.
4. Symmetric Difference ^
Elements not common in both sets.
8. Frozen Set
A frozen set cannot be modified.

In [ ]:
my_set = {10, 20, 30, 40}

print(my_set)

{40, 10, 20, 30}

In [ ]:
my_set = {1, 2, 3, 2, 4, 1}

print(my_set)

{1, 2, 3, 4}

In [ ]:
my_set = {10, 20, 30}

my_set.add(40)

print(my_set)

{40, 10, 20, 30}

In [ ]:
my_set = {10, "Hello", 3.5, True}

print(my_set)

{True, 10, 3.5, 'Hello'}

In [ ]:
a = {10, 20}

a.add(30)

print(a)

{10, 20, 30}

In [ ]:
a = {10, 20}

a.update([30, 40, 50])

print(a)

{40, 10, 50, 20, 30}

In [ ]:
a = {10, 20, 30}

a.remove(20)

print(a)

{10, 30}

In [ ]:
a = {10, 20, 30}

a.discard(20)

print(a)

{10, 30}

In [ ]:
a = {10, 20, 30}

a.pop()

print(a)

{20, 30}

In [ ]:
a = {10, 20, 30}

a.clear()

print(a)

set()

In [ ]:
a = {1, 2, 3}

b = a.copy()

print(b)

{1, 2, 3}

In [ ]:
A = {1, 2, 3}

B = {3, 4, 5}

print(A | B)

{1, 2, 3, 4, 5}

In [ ]:
A = {1, 2, 3}

B = {2, 3, 4}

print(A & B)

{2, 3}

In [ ]:
A = {1, 2, 3}

B = {2, 3, 4}

print(A - B)

{1}

In [ ]:
A = {1, 2, 3}

B = {2, 3, 4}

print(A ^ B)

{1, 4}

In [ ]:
a = {10, 20, 30}

print(len(a))

3

In [ ]:
a = {10, 20, 30}

print(max(a))

30

In [ ]:
a = {10, 20, 30}

print(min(a))

10

In [ ]:
a = {10, 20, 30}

print(sum(a))

60

In [ ]:
a = frozenset([1, 2, 3])

print(a)

frozenset({1, 2, 3})

Dictionary:
A dictionary in Python is basically a way to store information in pairs
A dictionary is a built-in Python data type used to store data in key : value pairs.e.g: a phone contact list: the name is the key, and the phone number is the value.
Features of Dictionary
1. Stores data in Key : Value pairs
2. Mutable
You can change, add and remove values.
3. Ordered
From Python 3.7+, dictionaries maintain insertion order.
4. Keys Cannot Be Duplicated
Duplicate keys overwrite old values.
d = {
    "name":"Ram",
    "name":"Shyam"
}
print(d)
5. Values Can Be Duplicated
d = {
    "a":100,
    "b":100
}
print(d)
6. Different Data Types Are Allowed
d = {
    "name":"Bhakti",
    "age":18,
    "marks":85.5,
    "pass":True
}
print(d)

In [ ]:
student = {
    "name": "Rahul",
    "age": 20,
    "city": "Pune"
}

print(student)

{'name': 'Rahul', 'age': 20, 'city': 'Pune'}

In [ ]:
person = {
    "name": "Bhakti",
    "age": 18
}

person["age"] = 19

print(person)

{'name': 'Bhakti', 'age': 19}

In [ ]:
d = {
    "a":1,
    "b":2,
    "c":3
}

print(d)

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
d = {
    "a":1,
    "b":9,
    "c":3
}

print(d)

{'a': 1, 'b': 9, 'c': 3}

In [ ]:
d = {
    "name":"Ram",
    "name":"Shyam"
}

print(d)

{'name': 'Shyam'}

In [ ]:
d = {
    "a":100,
    "b":100
}

print(d)

{'a': 100, 'b': 100}

In [ ]:
d = {
    "name":"Bhakti",
    "age":18,
    "marks":85.5,
    "pass":True
}

print(d)

{'name': 'Bhakti', 'age': 18, 'marks': 85.5, 'pass': True}

In [ ]:
d = {
    "name":"Bhakti",
    "age":18,
    "marks":85.5,
    "pass":True
}

print(d)

{'name': 'Bhakti', 'age': 18, 'marks': 85.5, 'pass': True}

In [ ]:
d = {}

print(type(d))

<class 'dict'>

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

print(student["name"])

Rahul

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}
print(student.get("age"))

20

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}
print(student.get("city"))

None

In [ ]:
student = {
    "name":"Rahul"
}

student["city"] = "Pune"

print(student)

{'name': 'Rahul', 'city': 'Pune'}

In [ ]:
student = {
    "age":20
}

student["age"] = 21

print(student)

{'age': 21}

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

student.pop("age")

print(student)

{'name': 'Rahul'}

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

student.popitem()

print(student)

{'name': 'Rahul'}

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

del student["age"]

print(student)

{'name': 'Rahul'}

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

student.clear()

print(student)

{}

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

print(student.keys())

dict_keys(['name', 'age'])

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

print(student.values())

dict_values(['Rahul', 20])

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

print(student.items())

dict_items([('name', 'Rahul'), ('age', 20)])

In [ ]:
student = {
    "name":"Rahul"
}

student.update({"age":20})

print(student)

{'name': 'Rahul', 'age': 20}

In [ ]:
a = {
    "x":1
}

b = a.copy()

print(b)

{'x': 1}

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}

for x in student:
    print(x)

In [ ]:
student = {
    "name":"Rahul",
    "age":20
}
for x in student.values():
    print(x)

In [ ]:
students = {
    1:{
        "name":"Rahul",
        "age":20
    },

    2:{
        "name":"Riya",
        "age":19
    }
}

print(students)

In [ ]:
square = {
    x:x*x
    for x in range(1,6)
}

print(square)

In [ ]:
d = {
    "a":1,
    "b":2
}

print(len(d))

2

In [ ]:
d = {
    10:"a",
    20:"b"
}

print(max(d))

20

In [ ]:
d = {
    10:"a",
    20:"b"
}

print(min(d))

10

In [ ]:
d = {
    3:"a",
    1:"b",
    2:"c"
}

print(sorted(d))

[1, 2, 3]

In [ ]:
d = {
    "a": 1,
    "b": 2
}

d["c"] = 3

print(d)

{'a': 1, 'b': 2, 'c': 3}

Functions in python
Think of a function in Python as a magical kitchen appliance. You put some ingredients in (inputs), it does some specific work (cooking), and it hands you back a finished dish (output).
1. To create a function, you use the keyword def (which stands for define).
def function_name(parameters):
    # This is the "inside" of the machine
    # Code goes here
    return result
ex: def greet_user(name):
    print(f"Hello, {name}! Welcome back.")

def: Declaring a new function. Tells Python, "Hey, I'm building a function!"

Parameter	The variable inside the ()

return	The final result passed back

greet_user: The name of our function. You use this to call it later.

(name): This is a parameter (an ingredient).

The indented code: This is the action the function performs.

2. How to Use (Call) a Function
Defining a function is like buying the kitchen appliance and putting it on the counter. It doesn't do anything until you turn it on. Turning it on is called calling the function.

To call it, you type its name with parentheses:

Python
# Calling the function and giving it the ingredient "Alice"
greet_user("Alice")

# Output: Hello, Alice! Welcome back.

In [ ]:
def wish():
  print("Hello dear")
  wish()

In [ ]:
def wish():
  print("Hello dear")

wish()

Hello dear

In [ ]:
def add_numbers(num1, num2):
    total = num1 + num2
    return total

In [ ]:
my_score = add_numbers(10, 5)

print(my_score)

15

In [ ]:
def subnumber(num1,num2):
  total=num1-num2
  return total

In [ ]:
myvalue=subnumber(15,5)

print(myvalue)

10

A group of functions,variables and classes saved to a file is nothing but the module
ex: every python file (.py) act as a module

In [ ]:
import final
print(final.x)
final.add(10,20)
final.products(10,20)

888
the sum: 30
the product: 200

In [ ]:
import demo
print(demo.x)
demo.division(3,5)
demo.products(2,3)
demo.add(3,4)

888
division 0.6
the product: 6
the sum: 7

In [ ]:
import math
r=5
print("Area of circle =", area_of_circle(r))

Area of circle = 78.5

In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr[1:5:2])

[2 4]

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
import pandas as pd
import numpy as np

data = np.array(['g', 'e', 'e', 'k', 's'])
s = pd.Series(data)
print("Pandas Series:")
print(s)

Pandas Series:
0    g
1    e
2    e
3    k
4    s
dtype: object

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv

In [ ]:
# Import pandas
import pandas as pd

# reading csv file
pd.read_csv("/content/data.csv")

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv

In [ ]:
# Import pandas
import pandas as pd

# reading csv file
pd.read_csv("/content/data.csv")

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]